(in-package sprite-test)

(defclass layer ()
  ((tilesets :initarg :tilesets :accessor tilesets :initform nil)
   (name :initarg :name :reader name)
   ;; render data
   (elements :initform 0 :accessor elements)
   (vao :accessor vao :initform nil)
   (vbos :accessor vbos :initform nil)))

(defmethod draw ((layer layer))
  (when (and (tilesets layer)
             (vao layer))
    (bind-textures (first (tilesets layer)))
    (gl:bind-vertex-array (vao layer))
    (gl:draw-arrays :points 0 (elements layer))))

(defmethod ensure-buffers ((layer layer))
  (unless (and (vao layer) (vbos layer))
    (let* ((vao (gl:gen-vertex-array))
           (vbo (gl:gen-buffers 2)))

      (gl:bind-vertex-array vao)
      (gl:enable-vertex-attrib-array 0)
      (gl:enable-vertex-attrib-array 1)
      (gl:enable-vertex-attrib-array 2)
      (gl:bind-buffer :array-buffer (first vbo))
      (gl:vertex-attrib-pointer 0 (* 2) :float nil (* 3 4) 0)
      (gl:vertex-attrib-pointer 1 (* 1) :float nil (* 3 4) (* 2 4))
      (gl:bind-buffer :array-buffer (second vbo))
      (gl:vertex-attrib-ipointer 2 (* 1) :int 4 0)
      (gl:bind-buffer :array-buffer 0)
      (gl:bind-vertex-array 0)
      (setf (vao layer) vao
            (vbos layer) vbo))))
